name: dueglow
description: "tfg proyecto"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.5.5
  http: ^1.2.0
  provider: ^6.1.1
  cupertino_icons: ^1.0.9
  flutter_secure_storage: ^10.0.0
  logger: ^2.0.2+1

  google_fonts: ^6.2.1
  mobile_scanner: ^5.0.0 

  image_picker: ^1.0.4
  #image: ^4.0.17
  mime: ^1.0.4
  
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
  # ========== ACTIVAR GENERADOR DE IDIOMAS (NUEVO) ==========
  generate: true